# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- sit

pool:
  vmImage: ubuntu-latest
  name: Default
  demands: 
  - Agent.ComputerName -equals prashants-Air
  - Agent.OS -equals Darwin

variables:
  buildConfiguration: 'Release'

stages:
  - stage: Build
    jobs:
    - job: Build
      displayName: Build
      steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '8.x'

        - script: dotnet build --configuration $(buildConfiguration)
          displayName: 'dotnet build $(buildConfiguration)'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish'
            ArtifactName: 'drop'
  - stage: Deploy
    dependsOn: Build
    jobs:
    - deployment: DeployWebApp
      environment: 'production'
      strategy:
        runOnce:
          deploy:
            steps:
              - download: current
                artifact: 'drop'

              - task: AzureWebApp@1
                inputs:
                  azureSubscription: 'CodePattern'
                  appType: 'webAppLinux'
                  appName: 'employersearch'
                  package: '$(System.DefaultWorkingDirectory)/CodePattern.zip'


    
