# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- sit

pool:
  vmImage: ubuntu-latest
  name: Default
  demands: 
  - Agent.ComputerName -equals prashants-Air
  - Agent.OS -equals Darwin

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'CodePattern'
    appType: 'webAppLinux'
    appName: 'employersearch'
    package: '$(System.DefaultWorkingDirectory)/CodePattern.zip'


    
